### ISSUE TITLE
Cannot read property 'loading' of undefined

### ISSUE THREAD

**Issue by jboothe** [kamilkisiela/GitHunt-angular2#3]
Occasionally, when submitting a new repo, the following error occurs. 

`browser_adapter.js:77 TypeError: Cannot read property 'loading' of undefined`

![screen shot 2016-06-18 at 11 14 44 am](https://cloud.githubusercontent.com/assets/3723481/16171780/57b2c9a0-3546-11e6-8374-8140d303a851.png)

A browser refresh reveals the newly submitted repo in the list.

**Comment by kamilkisiela** [comment]
apollostack/angular2-apollo#30 should fix it

**Comment by jboothe** [comment]
Discovered the pattern... 

1. The first submission works correctly. 
2. Subsequent submission fails with `'loading' undefined`. 
3. Page refresh displays the submission (that failed in the previous step) in the main list.
4. Goto step 1

**Comment by kamilkisiela** [comment]
It should be fixed with the next release. There was an issue with reusing
components.

niedz., 26 cze 2016, 05:13 użytkownik Jeff Boothe <notifications@github.com>
napisał:

**Comment by kamilkisiela** [comment]
@jboothe New version of `angular2-apollo` has been released, I also updated Githunt so you can check if it still an issue.

**Comment by jboothe** [comment]
Great, I'll check it out. Thanks.

**Comment by kamilkisiela** [comment]
@mention me if this is still an issue.

**Comment by jboothe** [comment]
@kamilkisiela thank you. App is working well now!
