### ISSUE TITLE
Submitted repo does not show in the list

### ISSUE THREAD

**Issue by jboothe** [kamilkisiela/GitHunt-angular2#4]
Occasionally, when submitting a new repo, the UI goes back to the list but the newly added repo does not appear in the list. A browser refresh reveals the newly added repo. 

This does not happen every time. I have not detected a reproducible pattern.

**Comment by kamilkisiela** [comment]
I'm not sure but maybe apollostack/angular2-apollo#30 would fix it too. I will ask Uri to publish the new release so we can check if this still happens.

**Comment by kamilkisiela** [comment]
@jboothe New version of `angular2-apollo` has been released, I also updated Githunt so you can check if it still an issue.

**Comment by kamilkisiela** [comment]
@mention me if this is still an issue.

**Comment by jboothe** [comment]
@kamilkisiela thank you. App is working well now!
